apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels: 
    app: app1
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: srikanth9959/app1
        ports: 
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app1
spec:
  selector: # labels will used here for selecting the pod
    app: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: app1

  annotations: 

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:010526266250:certificate/0b61452e-2bff-477a-a78f-e7640c3d1520
    alb.ingress.kubernetes.io/groupname: srikanthreddy
spec:
  ingressClassName: alb
  rules:
    - host: "app1.srikanthaws.fun"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: app1
              port:
                number: 80
